!include sprites/bridge.puml
!include sprites/message.puml
!include sprites/queue.puml

/' General Stylung 
'/

skinparam defaultTextAlignment center

/'
    Message Construct 
'/

/' Message '/
!define Message(_alias) rectangle "<$message>\r" as _alias <<message>> 
!define Message(_alias, _label) rectangle "<$message>\r _label" as _alias <<message>> 


/' EIP Pattern: Message Channel 
'/

!define MsgChannel(_alias) rectangle "<$queue>\r" as _alias <<message channel>> 
!define MsgChannel(_alias, _label) rectangle "<$queue>\r _label" as _alias <<message channel>> 

/' EIP Pattern: Point-to-Point Channel 
'/
!define P2PChannel(_alias) rectangle "<$queue>\r" as _alias <<point-to-point channel>> 
!define P2PChannel(_alias, _label) rectangle "<$queue>\r _label" as _alias <<point-to-point channel>> 

/' EIP Pattern: Publish-Subscribe Channel 
'/
!define PubSubChannel(_alias) rectangle "<$queue>\r" as _alias <<publish-subscribe channel>> 
!define PubSubChannel(_alias, _label) rectangle "<$queue>\r _label" as _alias <<publish-subscribe channel>> 

'/ EIP Pattern: Messaging Bridge
'/
!define MsgBridge(_alias) rectangle "<$bridge>" as _alias <<messaging bridge>> 
!define MsgBridge(_alias, _label) rectangle "<$bridge>\r _label" as _alias <<messaging bridge>> 

'/ Relations 
'/

!define Send(_from, _to) _from --> _to  

