!include sprites/bridge.puml
!include sprites/message.puml
!include sprites/queue.puml
!include sprites/message.puml
!include sprites/command_message.puml
!include sprites/document_message.puml
!include sprites/event_message.puml
!include sprites/channel_purger.pumls

/' General Styling '/

skinparam defaultTextAlignment center

/' ##################
    Message Construct 
    ################## 
'/

/'  EIP Pattern: Message 
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/Message.html
'/
!define Message(_alias) rectangle "<$message>\r" as _alias <<message>> 
!define Message(_alias, _label) rectangle "<$message>\r _label" as _alias <<message>> 

/'  EIP Pattern: Command Message
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/CommandMessage.html 
'/
!define CommandMessage(_alias) rectangle "<$command_message>\r" as _alias <<command message>> 
!define CommandMessage(_alias, _label) rectangle "<$command_message>\r _label" as _alias <<command message>> 

/'  EIP Pattern: Document Message
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/DocumentMessage.html 
'/
!define DocumentMessage(_alias) rectangle "<$document_message>\r" as _alias <<document message>> 
!define DocumentMessage(_alias, _label) rectangle "<$document_message>\r _label" as _alias <<document message>> 

/'  EIP Pattern: Event Message
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/EventMessage.html
'/
!define EventMessage(_alias) rectangle "<$event_message>\r" as _alias <<event message>> 
!define EventMessage(_alias, _label) rectangle "<$event_message>\r _label" as _alias <<event message>> 

/'  EIP Pattern: Request-Reply
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/RequestReply.html
'/
!define RequestReply(_alias) rectangle "<$request_reply>\r" as _alias <<request-reply>> 
!define RequestReply(_alias, _label) rectangle "<$request_reply>\r _label" as _alias <<request-reply>> 

/'  EIP Pattern: Return Address
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/ReturnAddress.html
'/
!define ReturnAddress(_alias) rectangle "<$return_address>\r" as _alias <<return address>> 
!define ReturnAddress(_alias, _label) rectangle "<$return_address>\r _label" as _alias <<return address>> 

/'  EIP Pattern: Correlation Identifier
    Link https://www.enterpriseintegrationpatterns.com/patterns/messaging/CorrelationIdentifier.html
'/
!define CorrelationIdentifier(_alias) rectangle "<$correlation_identifier>\r" as _alias <<correlation identifier>> 
!define CorrelationIdentifier(_alias, _label) rectangle "<$correlation_identifier>\r _label" as _alias <<correlation identifier>> 


/'  EIP Pattern: Message Sequence
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/MessageSequence.html
'/
!define MessageSequence(_alias) rectangle "<$message_sequence>\r" as _alias <<message sequence>> 
!define MessageSequence(_alias, _label) rectangle "<$message_sequence>\r _label" as _alias <<message sequence>> 


/' EIP Pattern: Message Channel 
'/

!define MsgChannel(_alias) rectangle "<$queue>\r" as _alias <<message channel>> 
!define MsgChannel(_alias, _label) rectangle "<$queue>\r _label" as _alias <<message channel>> 

/' EIP Pattern: Point-to-Point Channel 
'/
!define P2PChannel(_alias) rectangle "<$queue>\r" as _alias <<point-to-point channel>> 
!define P2PChannel(_alias, _label) rectangle "<$queue>\r _label" as _alias <<point-to-point channel>> 

/' EIP Pattern: Publish-Subscribe Channel 
'/
!define PubSubChannel(_alias) rectangle "<$queue>\r" as _alias <<publish-subscribe channel>> 
!define PubSubChannel(_alias, _label) rectangle "<$queue>\r _label" as _alias <<publish-subscribe channel>> 



'/ EIP Pattern: Messaging Bridge
'/
!define MsgBridge(_alias) rectangle "<$bridge>" as _alias <<messaging bridge>> 
!define MsgBridge(_alias, _label) rectangle "<$bridge>\r _label" as _alias <<messaging bridge>> 

/'  EIP Pattern: Event Message
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/ChannelPurger.html
'/
!define ChannelPurger(_alias) rectangle "<$channel_purger>\r" as _alias <<channel purger>> 
!define ChannelPurger(_alias, _label) rectangle "<$channel_purger>\r _label" as _alias <<channel purger>> 



'/ Relations 
'/

!define Send(_from, _to) _from --> _to  

