/' General Styling '/

!include "sprites/filter.puml" 

skinparam defaultTextAlignment center

/'  ########################################################
    ################## Message Construct  ################## 
'/  ########################################################

/'  EIP Pattern: Message 
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/Message.html
'/
!define Message(_alias) rectangle "<$message>\r" as _alias <<message>> 
!define Message(_alias, _label) rectangle "<$message>\r _label" as _alias <<message>> 

/'  EIP Pattern: Command Message
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/CommandMessage.html 
'/
!define CommandMessage(_alias) rectangle "<$command_message>\r" as _alias <<command message>> 
!define CommandMessage(_alias, _label) rectangle "<$command_message>\r _label" as _alias <<command message>> 

/'  EIP Pattern: Document Message
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/DocumentMessage.html 
'/
!define DocumentMessage(_alias) rectangle "<$document_message>\r" as _alias <<document message>> 
!define DocumentMessage(_alias, _label) rectangle "<$document_message>\r _label" as _alias <<document message>> 

/'  EIP Pattern: Event Message
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/EventMessage.html
'/
!define EventMessage(_alias) rectangle "<$event_message>\r" as _alias <<event message>> 
!define EventMessage(_alias, _label) rectangle "<$event_message>\r _label" as _alias <<event message>> 

/'  EIP Pattern: Request-Reply
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/RequestReply.html
'/
!define RequestReply(_alias) rectangle "<$request_reply>\r" as _alias <<request-reply>> 
!define RequestReply(_alias, _label) rectangle "<$request_reply>\r _label" as _alias <<request-reply>> 

/'  EIP Pattern: Return Address
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/ReturnAddress.html
'/
!define ReturnAddress(_alias) rectangle "<$return_address>\r" as _alias <<return address>> 
!define ReturnAddress(_alias, _label) rectangle "<$return_address>\r _label" as _alias <<return address>> 

/'  EIP Pattern: Correlation Identifier
    Link https://www.enterpriseintegrationpatterns.com/patterns/messaging/CorrelationIdentifier.html
'/
!define CorrelationIdentifier(_alias) rectangle "<$correlation_identifier>\r" as _alias <<correlation identifier>> 
!define CorrelationIdentifier(_alias, _label) rectangle "<$correlation_identifier>\r _label" as _alias <<correlation identifier>> 

/'  EIP Pattern: Message Sequence
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/MessageSequence.html
'/
!define MessageSequence(_alias) rectangle "<$message_sequence>\r" as _alias <<message sequence>> 
!define MessageSequence(_alias, _label) rectangle "<$message_sequence>\r _label" as _alias <<message sequence>> 

/' EIP Pattern: Message Expiration 
   Link https://www.enterpriseintegrationpatterns.com/patterns/messaging/MessageExpiration.html
'/
!define MessageExpiration(_alias) rectangle "<$message_expiration>\r" as _alias <<message expiration>> 
!define MessageExpiration(_alias, _label) rectangle "<$message_expiration>\r _label" as _alias <<message expiration>> 

/'  EIP Pattern: Format Indicator
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/FormatIndicator.html
'/

/'  ########################################################
    ################### Message Routing  ################### 
'/  ########################################################

/'  EIP Pattern: Pipes-and-Filter
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/PipesAndFilters.html
'/
!define Filter(_alias) rectangle " " as _alias <<filter>>
!define Filter(_alias, _label) rectangle "_label" as _alias <<filter>>

/'  EIP Pattern: Message Router
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/MessageRouter.html
'/
!define MessageRouter(_alias) rectangle "<$message_router>\r" as _alias <<message router>> 
!define MessageRouter(_alias, _label) rectangle "<$message_router>\r _label" as _alias <<message router>> 

/'  EIP Pattern: Contend-based Router
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/ContentBasedRouter.html
'/
!define ContentBasedRouter(_alias) rectangle "<$content_based_router>\r" as _alias <<content-based router>> 
!define ContentBasedRouter(_alias, _label) rectangle "<$content_based_router>\r _label" as _alias <<content-based router>> 

/'  EIP Pattern: Message Filter
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/Filter.html
'/
!define MessageFilter(_alias) rectangle "<$message_filter>\r" as _alias <<message filter>> 
!define MessageFilter(_alias, _label) rectangle "<$message_filter>\r _label" as _alias <<message filter>> 

/'  EIP Pattern: Dynamic Router
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/DynamicRouter.html
'/

' Does require a dynamic rulebase to be linked autoamtically
!definelong DynamicRouter(_alias, _rulebase) 
rectangle "<$message_router>\r" as _alias <<dynamic message router>> 
_alias -- _rulebase
!enddefinelong

' Does require a dynamic rulebase to be linked autoamtically
!definelong DynamicRouter(_alias, _label, _rulebase) 
rectangle "<$message_router>\r _label" as _alias <<dynamic message router>>
_alias -- _rulebase
!enddefinelong

/'  EIP Pattern: Recipient List
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/RecipientList.html
'/
!define RecipientList(_alias) rectangle "<$recipient_list>\r" as _alias <<recipient list>> 
!define RecipientList(_alias, _label) rectangle "<$recipient_list>\r _label" as _alias <<recipient list>> 


/'  EIP Pattern: Splitter
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/Sequencer.html
'/
!define Splitter(_alias) rectangle "<$splitter>\r" as _alias <<splitter>> 
!define Splitter(_alias, _label) rectangle "<$splitter>\r _label" as _alias <<splitter>> 


/'  EIP Pattern: Aggregator
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/Aggregator.html
'/
!define Aggregator(_alias) rectangle "<$aggregator>\r" as _alias <<aggregator>>
!define Aggregator(_alias, _label) rectangle "<$aggregator>\r _label" as _alias <<aggregator>>


/'  EIP Pattern: Resequencer
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/Resequencer.html
'/
!define Resequencer(_alias) rectangle "<$resequencer>\r" as _alias <<resequencer>>
!define Resequencer(_alias, _label) rectangle "<$resequencer>\r _label" as _alias <<resequencer>>


/'  EIP Pattern: Composed Msg. Processor
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/Resequencer.html
'/
!define ComposedMessageProcessor(_alias) rectangle "<$composed_message_processor>\r" as _alias <<composed msg processor>>
!define ComposedMessageProcessor(_alias, _label) rectangle "<$composed_message_processor>\r _label" as _alias <<composed msg processor>>

/'  EIP Pattern: Scatter-Gather
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/BroadcastAggregate.html
'/

/'  EIP Pattern: Routing Slip
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/RoutingTable.html
'/
!define RoutingSlip(_alias) rectangle "<$routing_slip>\r" as _alias <<routing slip>>
!define RoutingSlip(_alias, _label) rectangle "<$routing_slip>\r _label" as _alias <<routing slip>>


/'  EIP Pattern: Process Manager 
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/ProcessManager.html
'/
!define ProcessManager(_alias) rectangle "<$process_manager>\r" as _alias <<process manager>>
!define ProcessManager(_alias, _label) rectangle "<$process_manager>\r _label" as _alias <<process manager>>


/'  EIP Pattern: Message Broker
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/MessageBroker.html
'/
!define MessageBroker(_alias) rectangle as _alias <<message broker>>
!define MessageBroker(_alias, _label) rectangle "_label" as _alias <<message broker>>

/'  ########################################################
    ################ Message Transformation  ############### 
'/  ########################################################

/'  EIP Pattern: Message Translator
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/MessageTranslator.html
'/
!define MessageTranslator(_alias) rectangle as _alias <<message translator>>
!define MessageTransator(_alias, _label) rectangle "_label" as _alias <<message translator>>

/'  EIP Pattern: Envelope Wrapper
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/EnvelopeWrapper.html
'/
!define Wrapper(_alias) rectangle "<$wrapper>\r" as _alias <<wrapper>>
!define Wrapper(_alias, _label) rectangle "_label" "<$wrapper>\r" as _alias <<wrapper>>
!define Unwrapper(_alias) rectangle "<$unwrapper>\r" as _alias <<unwrapper>>
!define Unwrapper(_alias, _label) rectangle "_label" "<$unwrapper>\r" as _alias <<unwrapper>>

/'  EIP Pattern: Data Enricher
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/DataEnricher.html
'/
' Does require a external data source to be linked autoamtically
!definelong DataEnricher(_alias, _datasource) 
rectangle "<$data_enricher>\r" as _alias <<data enricher>> 
_alias -- _datasource
!enddefinelong

' Does require a external data source to be linked autoamtically
!definelong DataEnricher(_alias, _label, _datasource) 
rectangle "<$data_enricher>\r _label" as _alias <<data enricher>>
_alias -- _datasource
!enddefinelong

/'  EIP Pattern: Content Filter
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/ContentFilter.html
'/
!define ContentFilter(_alias) rectangle "<$content_filter>\r" as _alias <<content filter>>
!define ContentFilter(_alias, _label) rectangle "<$content_filter>\r _label" as _alias <<content filter>>

/'  ########################################################
    ################## Message Endpoints  ################## 
'/  ########################################################

/'  ########################################################
    ################## Messaging Channels  ################# 
'/  ########################################################

/'  EIP Pattern: Message Channel 
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/MessageChannel.html
'/
!define MsgChannel(_alias) rectangle "<$queue>\r" as _alias <<message channel>> 
!define MsgChannel(_alias, _label) rectangle "<$queue>\r _label" as _alias <<message channel>> 

/'  EIP Pattern: Point-to-Point Channel 
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/PointToPointChannel.html
'/
!define P2PChannel(_alias) rectangle "<$queue>\r" as _alias <<point-to-point channel>> 
!define P2PChannel(_alias, _label) rectangle "<$queue>\r _label" as _alias <<point-to-point channel>> 

/'  EIP Pattern: Publish-Subscribe Channel 
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/PublishSubscribeChannel.html
'/
!define PubSubChannel(_alias) rectangle "<$queue>\r" as _alias <<publish-subscribe channel>> 
!define PubSubChannel(_alias, _label) rectangle "<$queue>\r _label" as _alias <<publish-subscribe channel>> 

/'  EIP Pattern: Datatype Channel
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/DatatypeChannel.html
'/

/'  EIP Pattern: Invalid Message Channel 
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/InvalidMessageChannel.html
'/

/'  EIP Pattern: Dead Letter Channel 
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/DeadLetterChannel.html
'/

/'  EIP Pattern: Guaranteed Delivery
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/GuaranteedMessaging.html
'/

/'  EIP Pattern: Channel Adapter 
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/ChannelAdapter.html
'/

/'  EIP Pattern: Messaging Bridge
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/MessagingBridge.html
'/
!define MsgBridge(_alias) rectangle "<$bridge>" as _alias <<messaging bridge>> 
!define MsgBridge(_alias, _label) rectangle "<$bridge>\r _label" as _alias <<messaging bridge>> 

/'  EIP Pattern: Message Bus 
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/MessageBus.html
'/

/'  ########################################################
    ################## Systems Management  ################# 
'/  ########################################################

/'  EIP Pattern: Control BUs
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/ControlBus.html
'/

/'  EIP Pattern: Detour
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/Detour.html
'/

/'  EIP Pattern: Wire Tap
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/WireTap.html
'/

/'  EIP Pattern: Message History
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/MessageHistory.html
'/

/'  EIP Pattern: Message Store
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/MessageStore.html
'/

/'  EIP Patern: Smart Proxy 
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/SmartProxy.html
'/

/'  EIP Pattern: Test Message 
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/TestMessage.html 
'/

/'  EIP Pattern: Channel Purger
    Link: https://www.enterpriseintegrationpatterns.com/patterns/messaging/ChannelPurger.html
'/
 
!define ChannelPurger(_alias) rectangle "<$channel_purger>\r" as _alias <<channel purger>> 
!define ChannelPurger(_alias, _label) rectangle "<$channel_purger>\r _label" as _alias <<channel purger>> 

/'  ########################################################
    ######################################################## 
'/  ########################################################

'/ Relations 
'/

!define Send(_from, _to) _from --> _to

!define Pipe(_from, _to) _from --> _to : Pipe

