sprite $bridge [214x64/16z] {
tTLdseCs403XMNKXxNB_qwOdZf_8NmG6NEOlzGKLpavS236ctuenUCTd9pwLrcqrRMrPQgsBjTPrNRKlENwWJa9fjlOb1o_SKWU0yx4ikkgI_UU8OjMrQn3-
KxzJk5ZxgZNmzldIrvOSJk61wZwVszgpVskIQGa0yof8AHIr-fumLqop0xQgSW5SLgkEDoisAmxOgm9SjfvudoHRZzmbjba5XBQ-omyBo-1LngeMVbQ1lCSF
Iwe9U4ALAdU5PbLuPL6xXsDL8EMLhg0z0FvvrVkuGjS0uFj8jJwb0j7r1IxVDS935MDLd5Qnf7Br3YPDupy-dLOjMrGHALQuhcoPVt9FgkBoI0LIBN5DNflZ
6XNutZtd9zKYNAQ2UC5ocAp2RbMQLDsVMonpPgvtptvLdL2DpdLDFQSLBS7XglQ_AWXMEAb57SUhmemAMSxvNTugl4m5yOpVLIpmKXNIr75ehZTVjwXCHc-Q
dr51NZC75YpX-mELJQlAKDMdLRwtBXnLCSTfAhz5HRR0CRKkF5R9TQhGmLlXW9nMU1yLqheSCgNsgDmPgWPmm2WivjcZqg6gR53bHwhdH-7IXUDKUQXIHfKV
L4XhxAyrE5lbTgYWgcDVefLRuQrK90lioLdcVLK4IspFMsI_glkpLJYjR2rQ6DpoELMgHwgWrSqepwHgVKubjbj5KM53oHoJAbwe8flRZ7f_5SdyTjH-LRX6
HR30L5c5PrLjg5esgChaAtYBStzAE4SLXwhrEHNEyWHg5QvKCLRbQHMYUTUS0gGNXjKsgnBDywgb35uXyu1L-B7u2DNI0rHXKYKzCQtgTNpzD6lznkwNISyH
-IttMJaWMGl_v4ouvSnpUKav9AtydRz7HIwlg71ClJ18DF79YPQnzPCRxnpjir7ZqLOwdvzOvDz55RuWPu5RtXmVt7Yd50jyIU7sVthcQuec050pNrJk02Jb
greAuCpnNVK26lcoH6DAV5rIVmK
}

