sprite $channel_adapter_right [40x88/16z] {
xTT7aiGW40NHn4ZuqlrFEvO8bf_bJ3TQFtcNnTOITf3BzcZborEyTA5QTY1SR9O0uQu-Rb3k7Zs2S2vP2o2SorOz2EVBanq85veb1yB5RZSWt3N61ShTrY88
ztsA0OHpt_SQXFE_zreuD--rSiyDMuv_xuuxxhZZZZlkkB3dWhMetIp2IxgPN-DMRkMSTgkAj0DNh7ZfLhvg1zpMetAhAhMRkNvBj_9VkpbEEEbMbMi7pCia
tNn6j9jJY7Rp6Tbou6y-0G
}

