sprite $channel_purger [64x59/16z] {
hTDNaWCX38HX9fBX_gVTz3jGXOCaRxztYP6-SHzcwn-bxCMHvPBraetiv23dUNeVGeWnffHphibrIpzS-krqTVkalxbuIlhxmtxfpftfON-JV7yjpgtL_luQ
VefzCVVR_bFCX_b-VwD3iCulxRUu5_t-w5TMtwtxhvo-RiRxD-X5RvpFmn5as5yfzDTgcryv788CyzjE7K5wFpzZYG-M-RdHHf2-Nz238CFzqNCHPDX_MoaZ
IF_-JXT1-dukT16alnzwBkchUdxT7K6G-lz7prsGSl_e6GGfxp_euHTIpaVF84YvF_GCWdJpqJCAqir7po2ewVmKz8o2LFClUaP1cZvwnlYekNzgj4P1clrd
z8pfclVNS-hNNT57poH8se_ecGH9-mazao3f_j0p2HBsqJCbd-BxesSI99qVqJC94kuFFNEwT7v1pon8E1yz3mG9--Xv84ZMHyyZGR8-UXuA4jqVFGy5YVQF
deU29E-FzL4NGP8-UXwcYxAvVymt
}

