sprite $channel_adapter_left [40x88/16z] {
xTOtiiKW40NHnYC3slzglvqYKzt97nCVUKCJyCrp9P-huyuU1-KUrUCWNxDv7AHpzk1m48_dY0u7eSypEHpGvfKz3kguYyT1jjka7AHhjk1m4EqsAGUXssqI
3aARLzBEBZvx79Hx5EtME-9maCxXSl1yYDjkk-sssswxxUhiqbaKAXSiCfUJDMRkfUu0uIogXRFw5Cw2xjMj6n7XtQtQ3Y2SrRjm-PeL4AwCKK2vEkyCmbdP
2cUbhDpvz82UqV3CDm
}

