sprite $claim_check [42x41/16z] {
xP9LUiGm30PhjaN__MzRUSEBpuK99sF15ttzJlv9hRSQFdlDS8FJUoyg8BssuNv_AnfaZLNVgme-hwf-2UlJLUoGSsUma1Z5xQOO5nr8CqhO5ogSpfXGD-Jr
Ixc5PEmbJAt3uP9nesmn-ZmHRRqGUVWcBSnQZ7BVr35R47WiZ_qK0S9Yjddg0_HSx5WhhTE81bXyj4BSaZjXYLrAE7qkhGyMsnfQ8OnJb6pOCMKQBHyPW7hv
ipHwBJa-6Qm2j2FYyxuELMiCiJ1SV4iKhBJF8zz5bNte_m3_V0C
}

