sprite $command_message [37x51/16z] {
xT7NOe0W38NX0u4mJTx_QRk7DX1xs_5TENvbuGNtASTWE5WwKw3SfM2dJSAhE7PLE_19ArQou6mo5ew4Cn9OTE1gP1YrueeRZCQuIWF6IBYY-Oq_vG63cvsa
4SLkYTKBplB4GXGwtobX9IkTcemrqefNHHWxiKklNBfqWYFagfK3xYYCVVGVgRM8y9KJ1GftKHPLFP8RLMqKyj3aH54h00IPJjGKBr9reZcsgsFcKee2aBQB
kBLMQ_KZsE5Y3VkeQS2pekPFPWiWmudGj15eQlGYiAZg96mY_u3j8oUoyCiz0W
}

