sprite $composed_message_processor [154x65/16z] {
xTc5aGGn34JHCRCx_solbXcbu_u1gDumU5485oq_f0i8PPHHHXbbb5566MMKVT4xBMCCbodC-1m7DEvdyXbFomAY4SeCYli4MG7Gev78B81PdBOiOzKA9zXd
wsQsghA4NJs8P9SukUnG2-_85W0NEBaiuhHkPB8LBhqhIxcKMblhVOo9yvwIkRoQiHhHnxoOKT-MfHX3yDuvQytfFcl-kQFfJsPSx36b-zcXRDwxqrvicehC
droQCjbSRPgsh5Z1qsbYLVUwTre7O4JPStCUDarHPb2Tz8dUHn0yDt_0kyQFb_tSDyU5CSPLHCeeeumooYYZZ3BAVl6RumS
}

