sprite $control_bus [114x87/16z] {
xTg73gKg483X6K0GaVdV_srlF6BkzZLxPBR-QQP-CHIh_9nACwPdhSXeiPfKfgUfsY97sO8u5SaYig3YbjeYOb4S2oQbYckrj2IkfMOghgaXpl7JnRBpJ7kv
9rgFyamHkoCMvBbwkI7kKPuhxZT4vCduYyH_uZynbkGhXWx9LLmCYgku0bKznGOqJr4xq3t5Q805Hp4RG78KLuwoezWuAdwYTewgkedHE6f-OkPL7sAkoson
WkrWKOwIGPmiDjWhaAw9op9N31ssR90ldtMkc0nAD5WldwPJnG8i1xJfk73HvueLBCWEkuvXX3XJ7DO6FOnXX6Mc60msbGh4COompXF7n1cZEOOHDfqe5Y2T
LBw6aVwu64gzwc11P2oF1hO1CPLrLC8JOkF_pacg7JOD7LesgFnV3--BslcmgjUKNGpMQ7nSV5-KtEt_pWVe3IoimA8x7sPL7n15F-Z_Mu_O3lR0WJMSwQmd
dGoK3aqF_2MFPed9O0VMiIYhpXQ3SMrmqO0aiyKnVosSXxjE5wNzVt-rGfRvuiR_UtYCuY2kOnX73c8sm8AZc0newYW6kuRnlgXlYRe3YzmNOmUsDqHfOE6-
M7XbRuZPg7fRZ8pwZuiIayXjSULAdTwIxLmb9z7_79LH4oTH8cVY9efktVRy5x_HzV_2Khey5qNEScrh_8eeHfHdYjtabHf7sUzh8AFrVt5UD_QS2JMkafDO
kGfEuiB8v0nJcTlsyIcgjIGUSwT7EKkjL9bUI2fNjOW5SIoQo68gRYcBY6IYE1Kik__rz5F-xFeF
}

