sprite $correlation_identifier [81x51/16z] {
xT9Nikme48JXn1IUoltlTjhe64GBQQvtttF6Bo241vULr1fmWPJxDdiSCqrB319oKuyJhlSSGuYbDtlOqoARf1PBdaasMOzwpF8kK9RdOvHtYHQlj2AVn74r
CfhaawHumQiCQiQXs6JG0sOboo0GJrBfCEfH1gbXnY2ZVi-umXl1mAhi43FAJXEJb0_137oN7RNOCoexDGWtkjDakisL4tgOgBpp6DZvX0QJbcH4W-qHwK_U
EofcgSeWTMp2zFsQPL0APePHFkk2Gqw78mPQl13xvvKsB9Gkdp0ThFXHhCGIAUzwnu6aMHvYRpXHUvA7f1c7N6EhjQe6d9AkjsbZyrWn4XaiBh4XKWnE4TSH
-9x1Vy5_GKx-_tOShK-ptlx8O6Aw5coyw_4isBjU37RllHJAEkZewAy56-wqh8EvePN_5Sph80C2pUMWYNHpCDtaJDm83Gp349otwH6aglBLrgSOOmZ4JQtl
bnb6urOUGOqnfigmketXapqQONh3hAjWPBXZkXuKsaMm5znL_Hydf3aEEWhkX7uH77xipBAuSYQUM2u4UTSJ5i71EZZuKS49HkljN-6V_m
}

