sprite $datatype_channel [214x93/16z] {
tTm5akj8383Xlvcb-vzsUTzGucUt2rJ-YcS2KjHeuaX8kLHpUX-Zr-pP4DlIsLkrfKtHELgjVOYkp2Mkoie1Q_AI4Zw2J4Edlv9JzPYJPGI-Sbc7vvGapM6E
doFmGjN2xxc-FFPaoRpcvd9mp4l3e7RKWOe43aL963G6Hw863WID62ITOqdJSSu63UNGSJc2H0pgWzyB6dZ9Iy2WqZWZYkELcJ4eYEEKEdcXTGno4ZbfLNv8
2ujwvIodWUyaO50GpikBRrh3efMuOEM3tyIEChWYA5-CZ4NYkQGt-10M5fNEDLxXmqoFA1MCze1I7HQhPonQWSjcuJzEiU9sP_zOJDI6HRsmGVr7fIrITjHX
Ugn8uzOQgrOiwfaj6W1O7el4iQLr02zO52TxeW3aZaMbiaaDJy4ZtjgzYCCYTMng0_molR3ON5waWKMfiyihb8f5jR1DeISi6ebjAncTWs-5DHgAISg-EfnY
aHFsvUaN5jqAAwquiEXMM45IVzfq1Lvpmw9RORc7PbKg5jqBwqbPFJ-hzi2i7ZfQfFx4h1uv2qkOM7Ghh2XEiCWB-_9wulwgpESTE8FMcH6BPc3RBBICGRV2
qa1kM5GQkvn2c4_R30S158kStXa2OGOiMe5DemArFcouK0_4-QoLe5Umsx7aJhU2aR1enkqv620DB2hjtk2fJrgsvmMMc-0A-mtGxYYO--O8QFhoBATk_-8i
eFJ7NCca7lxZn65GaBsnmlXrZoDpaKJu8DvciRPAPRrdZNodLB0Y1dbnN50dNqN1ZDqExzNnJQzO987JPZsuASsKj3Whoy4DXCQqpZb1_S5sovgPEKKoB_ME
GLuY9ypE6wDZK3WpOinv-3-3eePxZnzO4uE2HWwDnQ4s7VO4IRpdve1ZHJBs-DLu9qexym7TOuvh4dYfIUICAirXJbmZy4FHmKckoaYOaxz7vPiCptakJnar
UeSfQVmN5TxdBj8y5xbOnnArIcODlFCd
}

