sprite $detour [157x50/16z] {
xTd7bSKm34DHK78EGl_TpZXJo-ySU4lWErm1FLEH3MwAdHQtbBANuuQaPYnehTPCKfp4Pz7b9E8qFnESGV2lPGUtKw3Ja8tWRfo3MPFqjYof9Rq_I-e1OqbD
YViIZtUnBvK4nfBUcoLDOIpfhLbIf7W5I-fJXq66doM9u40DoGhhE0PIS9Z0Jh4ggR3dy0lfESrhoI9bBo1RFv9KYUOr5n4H88nQfT7g1RThwqKJQvNGoLPa
hR66Po_5KOGTh9FpNudZI5aNWfNIgixm7dy
}

