sprite $document_message [37x52/16z] {
xT75WKKn20NG24IH_giTTnwC-x-ho8cIhWDZhOav1Ub27R4jcJxRkzoqXdXArtqR7JNNmrxZ8rEUhDtjQAF-PD7HLboU34YnICrRmPWivlpsaftG8Yd-9VtN
YI5sSFLqa3NkstvTUDwtGOjRuTlLNMhoCcGXL9ooIlAJSMrPtI7-hyReXDJ48hlXkn3fHMZc6340TbO84LqrILw0G354D-rkKAqL01uYcK_Hfeli_GWDfnBs
k1YXmhCeCwK8CG1qaMfHM1Q_db-1JD8Vppa
}

