sprite $eventdriven_consumer [104x43/16z] {
xTWr5iGW00JGk8Uv_ssNRbFXpapF-xWDto1C1bqmX4WUXmuTEdJe7DZ65CuDu5xIE3B7bCO1tcsqSdPieujZs7_GThZUaJadS-TVu422EBNdS6XFYl59CD-4
otmxfaRsWqCslvDpWGuTEdJefFeF-G4
}

