sprite $event_message [36x51/16z] {
xT05Sa0X34NHXoP1zx_QwdUaxZtZpCM21vfIBaaiXbGeOhKob98P9PcnS4NraqhOc6hG4GK7fdUIAJWHHaCyJdH1epcxyxVQlC_XGfN1vVDpscbdqpxmYXad
9lV6h72KF5eSSH0IUk9XcIhwGhRBlI4h3BXSX3odGfZGn9Ki6jrXplqtg8rEWuitDAe-IjD6x3qpRJmM7zHuJqIylBdSSzV6YmZpqaIwfzjXj7TzIjFEi6qU
vM5py9QcWT_g5W
}

