sprite $invalid_message_channel [125x82/16z] {
xTO5SXun30NW9pFh_gSjxD-CnecJ3abRs2-CCZpBYntvc8gE78D3I3awd8GorkWrwzIkRImUhVJP0zwBSnGFHMwsrwJJBDZuEG9K4IUyuGw8l0BqQuiXSqSV
16Mz0e9aicD0MnpO-8MNEg1k1knwUkstGUtOyOvRh-LtKDSZthjELwrGHumFShkcho-ryu1IWxwQyT5orzAh6_wKWqGB1XW7kVjnM_4qOeE-y_B6cIlqkOc3
i7A1llFU-cMoxETU4gP9u8ZF5vsxywXX-hkQJCimYNjDn_PgTB7KJ_QYvNkwJEhN3mZgHlZa-Q8q-mjT5gDNg5iUkrRa4LvRwfysFLxGDjCU0laITJheSjl2
yvQ1j9foUSzHDfoneRnQ9DsvPteDexTJA7ZKagAELDhaccFfA-Cef5oRZbfITAcq7F7tUJnYYRXBPUQ6UqHUPN727MXoGkJbS8F20q3d2dj-iPSFnZfNMG3x
j3dPUaDIacGOrcbpVGrldpc_E02TcGT9vYpJHfFvMlB2tJvjLt4opPmK6ymyVsME3DDsrRhsNBR1XBlI1g0nSvTsPvQs_KgrovmqbSBCLM9WcBQzE18lialR
LP0vosOKczxsfiv6-m_qqoRSjYITjDCsdPJkg_ij35PfUsioj1y3FVjnfbTltxR4ActIuMmor_QfkJPbpxNx72rssD3X5xGChlahbIT1Irpy6mbwV2vVoHwN
n-FnU7m7
}

