sprite $message_router [157x50/16z] {
xTP7UiKW30JWeMDXqFrF-uhI83ta5Nq9_zOh0z8Cn5AO2vJYimAL8ei0VJmL7hLUxUrFF6x0vhR7o292c87jkMS6LnVtbYq05b34RLm282hp3ZLCgZKPQ1GA
RmuQoGn0cNu6DFB4vF53QmQQqXbmMoi16fbOMpPh1jPAkqsigv4AkTcL5eW2hgZoIPYBzSGd7bUJM9YP6V0iF7x2nPWwkRVrYAYne9aPo2mg4Ms3F4WTY_3P
vpW8EuluYrEd44UfaqTkvcemmxAmk1hBpCrWYkCJXokomMEMyTxW7rYMPLcMHNdmM-R6KAWlcnf55fllkPuT66DmCvb5BI_sGUsriu1RyImyLDhu946fI1Jn
Tnm1
}

