sprite $message [41x72/16z] {
xTQ74jim30DGYIG0IXxw_x_jPNJuSkpUBMvbF1l8Jdl4AQ9zCZoFaMDRqp_A-hxPsmFuCRZo_J7BQxVF3yz-e7BSBbVzhE1fr-kpcEb7kmPRqJpQDRteLhuy
2TzsnjT9TXrTDsKMSAfykgxnitzuTMojYZwKNBsLoUMNW-hWdEYjUvxRqvNXTgxpI6kVasoVcVNPy3zSBwdWC6Rso1MTUpOleKYvA0iDcCuIEaY6J9GZXvTG
gI2W41GoA-76k26I18r72Itq6Eb4v8mIOYWWqXN4nweNEoK7Gw1prTMMf0a44Re-wajYfeT2_XZQwsfqaY31a64lOJT1_dY6Ga89NGa8kizKj1AUyXk8nqlp
aMgtJ1ebW5Hc2MsDQ8CqROeONiB1rdBtvXkw7HebVCblyYdy_vNYVPjcAmrJ9euI7j7t39ES56Gb3CaakW04fHBs67A5N2GpPWcdXz8LJzjBg04NWv0BKfIm
JJ9443VBkfect4j1SfYNy4pJOo8OcLP2qqsGDqlJLd_t-7qWRfAZSrL_2YRl0n5YOAeNi2rHK8WtZnXPGYUfBHGo7R1HGd9tf9n3dLkq4axFQQxPOyiMUvJm
9My
}

