sprite $message_translator [74x39/16z] {
xPO5Zi0W44KNbnQu_srtsisiuHRbHuiyHduc_LYd46dqMdInZHHVEwGV7P9GT169QESDxoSHIUBigBg35QI3nE5vcwuJaLS8YhQGdgEtPiMA6-_WH55S1m_X
rtl7z0q7CnJw1AFQN81vNf94mHXeZEZsax3-ToMeUeAXWyvaQ0vkF0Gpxd4qXyTWPaW2McaqvZLAOX3E9Ry87CtHJI9lCFnd7StHHy9W8g4vsaZ2GXu_mKHw
zqiaJ20sP2oc0vWZIoBo3QPn5b25RqRpwGvMagxvH8G5SqGpKxEXcSaDsJ373-cG5lvdBjCd
}

