sprite $message_sequence [82x36/16z] {
rTG5ikGm38JXbbc9hBx_QPSXOFjDblSh7fN-2MD0yhQRLi5Cqjss5l0YQRwN58jo6pUhMqanDxU8LoHN-RPQSHDi3_WiUy7RigVZThi5ZnNPzhU333Yo3IUH
6KTgRvvom9dh-GWJpZR7IlI8gtuyovvnPHlcnDFwHwkuiugfhOsl1BweXe7W0MCfTGofVfxFLejXg905Opq1YAHYRAyOQIGnzkdWytmkBXZOoOp5GTJvCQ9j
6EZp888Bb0rJ7d6d2NEgo0rpsV0RyGv7pyV4rMNbuVYt5eClLaHxLvaNg_cUBaKnBegzbz9TPcDbBSPuBCPEBeg50H2MMV7ZHDYEHSbP5yLc0E1jCWvT07Iz
NCUyA8Q0vJ5-L1XVBtws-s9Sd0NFYi4OL-Eip8-AcHRMfm3r9yNAYlauRvy3ydenCcDLP0HG-U0Ojnu_aibOtB9aweDYvoTrCaOqalgBlnJXztrxViCNzt_m
7W
}

