sprite $message_filter [43x59/16z] {
dT9fpkGW38HXPm_x_MyxK282Iutj-Uht8_VRISY-irX7PwIw3TlhZhQpxQgxx-TvdVC-n4nKDXDDdYYUZCAU6AFv8dfUVdL1suyVqHBGKX6hNqskqN0PQ4kj
iOxzhTy1U4vq9FrggAR7QdyBgOZLAL8HgxKY5R5QArAniYi1qS4XLhcQJZZ4AfyBKdki683K4IjIf7wnjnI0r14h_gr2OtkI0ZnIHwnmDRupzRT0M-hOxOLl
0AaZDg-l-aXi-LZ-BQIos2L5AejTjIALnwvQ7L9vx280gJpsMLn5AjjHLgFVAuJRE7nTNIte9F-7tWeTqaPnyrOef9KE-LWeIX-53ccZNRuoRT9CXpHG_Fqg
dKAdewzEktJArVceGcUfq_lxVI_JJrfeirqg54VD5A5D1fbEHqEKAH_zTVy
}

