sprite $message_dispatcher [100x55/16z] {
xTW7agGm38NX9zau4FJkVzeDhXuLC94fj77-0_H7i8MhyRlYlRriuCv-j_5bP5A3ZKJI9DHGqf48mmboap13Z4z8bA56RmuoiDBhKGOs-cs469fhLUDemUr6
RekHvFPuwojkDvGScM0WMyG-NpZI1uW88mqY1yv4QRQGBFYaaQhYdOfr0TdnMQFqtYV1EV67dhT50PIANKQzQFJUCWxvuj5boo_lHBrcZ6ew4kGAwLPUcoWc
rutzCziuMgtvpsxJUI6RN3AybfquJ0mOoNdSAUR3U2TAVTvSQstDwwSEmtNU6wHLGQUt3aDFoOzCzfMZK1IwyOsmqZEv_gnQVl5ZTxmFR6uehXgJd4SWsqll
mn75DQEc5muVoPSkrdKwVzGJhXWjlpW3TMp12Tu1IVYmaNlHjmw3ULt7huaSxpFVEdSdMnGWK-Xvjrgl92N4y3f9MhpX9mMk4ORiHyj6pX76QXmzJRD-j-4d
kBvkkd3KxZUyXOzgcD7fbI0Z6pqBCf3eX4GPoFJ17cPWuYWXq41n8iv09JE23UJqzP_CyxwCU_iE
}

