sprite $message_expiration [70x69/16z] {
lSy7qgmu303XbdEGnVrlkxm_Cu7aglrcW4fkI-mGdqgjhTMIW-CEINMOjfnIZ2cNFXOjWMjINrfoR8IYLZrdIR4MUSNbeP5JYbN7Mr57u52oAcmaOIECxjWb
NJri3GTRsH8xWXKuhk2qoSusWLCLgEDT9W_XR8LahpDf2EShHEE5l0XNAcHpEnFkLlQFU1EkLiZAbWMkL-Y5lrhbhU5vHpQNXy5x-hwoFJZ2pGezyoqtxbQS
2L_CtQvG2vzIutv5Z4_c9ohK3AkWp5Jy-8hTh6nMCPchb09uPQxY1v3BP8L5e0VsQM1VZv-bFSVNv88OivNOy3fTyKfiqnKnKfski93B_rCPDiRGLL-rLQsr
b9BuON9S4RVogx2ACQPLpZdnOo5LfYt4nhI5eCno0p5cnGuBit81zKng4KfcaWc4pXndh1RcfCggHwPeO1Nx_48h4oQKklbUjfr15k6stFXI2xUPvukOuwPQ
-P4wzpWJVcdY5atRfkE6qjY8W-k22LkrSvKtpwFUkCOjWMUgyv5LxvVMYRpML3WfMk2TR85Jwl2xSnQE-T7O9TKI-wHPv8XNZNkDOeKpWbeMNWfrAS99lfec
zvGefbcu8jHXlQJWdJZdOwwwQ75S9p7NhiF6q5QIPyT_
}

