sprite $messaging_gateway [94x64/16z] {
xTXLeYqn24JHYXE3-O_s2TTT-jHVzW1MkmHSBNNGIbCDztLxNSULujIAHzq2NXRiYZsq0SzqlExtUkXk4tIt1U3eGLG2IBfeTvkXDxSvUjKH0OvUTRhDqCkU
2U3eSI-tERfbWAY3fn_zw4S_-j7BI4Hzcgb4bZxiVogHedUxJrkawTvkySQws8jskwgNKcjh8hsFCRUzwge-HkyYqcgj9VSNjDRRdfbgJyq4a7HjWV2ichSo
F8Ok4Q3eoNOXlYFZURzxHpzwO-fXQEFfFkwfFDt7O9Mbkxzs8UbUNZkpTFVtoYJTAtibdkwJcaJJtH-Hf7lDVPBkVWyy7K6KCWT-9F8dC-o_
}

