sprite $messaging_mapper [127x36/16z] {
hTO5bgum30NWMxV8_bVxN63IOQ3bE_PB3XUe1Tj2UgRKvF6II4fzt4UiF4Ibu0sT4vwe_3kt267Vw0_h1_vInIuQ3zC9_p5ZJvQ7zQT09nqxd7XCTUtpUeSZ
hm4RQiDK8r23rIhEEc63ECnK0a0L7tbJxzG3Qk6ED31Js05mNCmVRRfmRDYz-9xdqz7z6UYCCxOZdMGvVbwL_ar7Bmb7Nc2fNuqF32kAF-H57EGEY-fgV6um
WeHFlxK2guxL-9OdwH57yPXF4LRYrVYUxCgATYokbscGrVWHJNgQpSJBY_hbU0euSPpdw_3geaxjxrsNC6P6lOg7llNqg0IBwlNBrzV67eriUbkOUeip7trS
D4FiNuslzQhtihVJ4wn2g_5nmAA6_zeu9LLOlQ_6Ey44LJCLhswNyseyEC1oN8xd_f6wsSHVYBU3RtUVpExh_g3oUhSJ63DE4e0axaPtn0NhA676IqGK3uEZ
RNOsHCPKa2G1LYASISKEofWA6kxKLy4M9m5tsOOWQS2UgE5XVJoaP-mAal24rx_rHIls1U8S_NsHf4IVYah2As8ZVa94LFul-Ey
}

