sprite $message_store [64x59/16z] {
xPS5WWCX301nuld_RozbENUtJbqcjfuU8PTQQrl4cr9oUW6b3K0MStTJLJdGuFXA24Ol3wfjahenuHozHRwwQGUzzp7cARYOcs3FDzE2kk1e9GTbSyzV8SQS
4OL4tQWVTXU3bbCENkW38Aus8NJmbeBR_htwsrsVY5ZSK_Dmt-Yp68-T_jNrBz-zkc5v9F-Z_iwlxbWbWodq_Chyl9QZXX-v6uWhmMZb1JxGSbKuNWy_o7KY
gvio8Smn-k7L6-iEXgZcRYAyvxVpN_TVsvYd_ucQ-JLc6lbEeM7N_uZ_MFtjtlmVyLypVnRxrlpRVyVwPz-N_slhRu_K_qxVtjl_hvq_VS7y7yd_5xR_y_P_
tlxFs_zv-pzl_vxVuJkcwVtDv__c8JOnRFdLFglPJ8ionPLUSVt3egxOqWtg834NHfYZjH3l-MF2FeDMXkNU8zS-WKJjE6KEzjNVllnZZE0blOXyrKC9Sdg4
2m
}

