sprite $message_bus [36x115/16z] {
xTU5jSGW50JGmUr9_zL-PKySKW2plhbn5FlOb6kh9JdSnsPM-G7vXubAlRh0KfpPVhl4aa-2t7N3HTBsgx2_ttsbpwQfuIbP_n4tF2U8-QKDeqG2p0ySXW9o
mJYUq3mcKOYT6RPl3BtO5qsFMT1qTkuAgcr84eaHq-g013LirK3bUIjYG4xDf6nqCofZtOpBwcO0cwYN-L9PkJZWPBhp8QOKmxRZpOoop2dBBBFCCiiiiymo
oyZKi2KtCs9Qc1b5YHDY1Puc9XLWEdVmG1llp0W09qDJKtz_oBO5ExgCr8yay2FQvZ2P7aZHxNjLSqluEAzn5t6PB7bf5eTaIJWdIei6FRv8kTrzg4gjvDBe
XriynVcOOd2dJNm3
}

