sprite $normalizer [136x65/16z] {
xTQ54kH020JGPjo0___QqzNiJgtDXRDNdhAk19hWz-EA0-mH5oQO8yx8za4m2e0oOAnN043jCDKRVceDXbhV9B9H1yv6XP4ojXDh8ZFTRB2198Hh90cxY-Am
vIHYPq4SRZa9s9SNFtcwio3-Jem0M7-PmrUndrII21E92MV42NU9xjXaynOBtCf-pJvlTGuaX5-izaTNBdMWj9qk__pgapW0gsf5Rrp_TxIEYL8180qiePW_
61LrOC8THeCZ7dFkanmORM2cPHoM1e-fIdRlvw18cF22WvxnaEWtdDqREHuOyUe3FS3w4sTQcoCEdDJoL8u3JhGmX_Zh1NvWwAMHQ56Et70XTzn3v9pt8SIO
M3VMvDY-WNi_BAeYp6FqtbhTvEX-JOvQ9jCoq_LCCYsQ3oUJxPbgvza8w_QbfqcRJ5NzgT32_WWyQTS7EJXYQOznc5oRkQ9Q7R0qH-hJwpkN02pEmNeVhRxx
1dwZ73VmWl_-IrrKk3YOYj8YWLoHJh2JsUEWCCoaovPiJB3XXN2XTDZONdDnlqVfbm8BiUEQOrX85TT8O24NREW__JuytmwCYUsUjWGJgMzg3KQuu8mqmWXf
knZI0ZlS7Nx8ac4f2TTIkpOFOpxb5F7F-We
}

