sprite $polling_consumer [72x43/16z] {
xTQ5OGCn44JH4SDI_zM6cLSn-tu1xq28NMMx2OPTTFREvgHEh4mjhZef0QWgFQUGyb3EQuvOYy89pnMX5IVPNGLlwxBWaDtLyAv6RYVQGntlwknrfZsKyJwg
FYVONThmiQG-fvj9mHTHSJac6LzMf--xy4r1TxI-R4UEXbqv9_LTKNRZjBuRX_DEdCBmEctYSvBT3gZZOzRXTu8El8zuxRpW6V1Qv84r1qFRinI7LgmwYDDu
jDg7QF_dUPhkb5uZ_j1stzYStNGB
}

