sprite $process_manager [106x60/16z] {
xTPLOYD134NHfsAKzh_QcQ22vbQ7wloOVGr5k9YhWrk1lSmvKAmJrX8xt8jCC4NYyAXqc4fLhmh1KarwTGHOQl7DLKEvw5NZ8U5rT8S9MxK_3q8FOo8EGE04
SsdAbE6mXzInazX-NccLLccLGiTE2ZlimOqHkS1UuGHGvGXRaHizRRxTmOxhq-DPvc9vKCOhr6Q0XJ0xuQt0ZR0rQXm-7HyPsqfSZlvrbvD30WufSiZnqi7H
NUd0KRCJFdTDIMViMpg3DolfAkGF_7jRbLJY-YxjO5E2_bZwSzgKTBdJ8M9LqkLEPv5PIPUxn1cuk2H7uSdjJnB8MHzBRdqIBYYjqYgjqYgjqYfjkXCUBsr8
ZleF
}

