sprite $recipient_list [156x49/16z] {
xTX56gH030NWbvHHbjp_jaDdh1XjvSk2Vuz7mMaubm2VWku2F68r4VvmLJEAoKTf4NyWd24DgMh6TbCFsg8l4ZukLEt9upUbCcSXxABk2jo8NMl0Dros22Tu
av7XKHwoCHmAJLl4mbduEvGi_1tYAZt18Rg5Fy6Xw3NyhPJv37-tfSmw-NzSfOpfjqv-D-AF3zPFTdAQgeAF8RsHvpgv6iAxq8gvgYdFbBAafZBJ0VwXYEW_
o86-JERz9omW8jmfgmdFz82W9kDkX8SqtMtMEnyk7brly3bDPW5CU7JcsAQqCsSrgG5UKP6P2UOQZaxOgQvTz9abnl_4T4sQgtGbnjb5xzgaZzE0_w9NfXId
HQ_hhhhyKnZK98_JG5SZOzLNRLLt4IV9QchuAHwaHJO1Pr53S4bt3AUOyPWl
}

