sprite $resequencer [152x49/16z] {
xTa5aeGm48NXHUB9zlrFE-vlD4LZzVxI4U33xM-92JGF5p1MugABBe5cue8lT5rqqKKNNGBL_ABWWY-gVgbt1JET2xh-reX8CXEuljkGKZzFrwxOpyq5jBcv
TeL-CbVJ6sEjSzw74ACyDh0BUkaoASKOWlVEMMlahjmFknxh-vThle5HJkyg1aOvfQl8eT32AATt5GjVJ-xA4ZkzysFzavAcKJXlLto1pSwbVrt89n9qgKON
HXTTTD555z_iRG4
}

