sprite $return_address [64x72/16z] {
xTLLSi0m38JXDKe1oVS_RHcY56MNw-_zd_K4SQDksbGuealHjGI4oBe5-94at661Mss7qLK2V9AQWZVuh0H38rmQB6Pub0rM57ZK1LPGU13Zf7tfVfAd5yH5
8uormgNQlQHm4iQZq0gSGbiF5u_X9zlTDI0bzAWg2ozRMnCwfKgrO4Z3cDaVjFSolVymdzYt8y89oRxBrhyVrfIO-_Unv9ovVnzCX95zOcOQlVv_gZT-oFdv
1TMn_-lEFw_VUFzUN_J_cVzFPu-J7zxFVlQ6jxVYO8z_slk_FvS
}

