sprite $selective_consumer [117x54/16z] {
xTXL6Xin34NXAvaaWxp_rHQcNvYSr9xY_seumI5i-hwmwTZJxnVz7oNdOuh1yMvHJjLgKT5ScwdV8-hhUOXJCLaTzRK5N2Arj3Gg5d6BS-DrqL9nNpI_AjeK
ZpYZDT4kU8oxNn4j6Syuu_bHgNWk6CsEEiChacT7IyHBndEZpl1QodEZDM20kPbH6ZnWoQTHfv5n9MQCSEtJQ51L2OHpEM28qSVHZNYwc3H48yxGUDJhGNA7
rOOnIIwsxkhUZ6xYjeeRniHy6UtTX0UY5FHI17p1cCD48cBc_aDBTw8YUY3VwHKWAiPmIrl7p5fh_L1zy-FLo7ZxdHxObXJ6Mr7nsBYACI5VHGz7ik5ePFpS
hrU5nez8tucxd3H64gwDHmFXGl4OqlZ3A8d3jQGOmORteZDsIpepYkOmeFgfqL3nMgYO5Hs_T6XkSjGtl18B9aUH5Syvu-bHj8Hdo3pcHya2dkW92wBW9_jI
4oo9WflYFcS9Yw90AOmxadciYo9Plib6ouoLqIqR2JXmqee35aT18VUg4drCcdiLjzSJi-_1aYK6-WsU3VwF_e_kwoi
}

