sprite $service_activator [121x55/16z] {
xTa5jkqW38NXJH825SZyP_kWrxLvNPnUwx_qw5SNYk-PkSEpEA_LtgskcNqmd1aUexba3dYtmBaiT1jOQiAd9UDRm6o2dTXaF4oUsP5Am-4vmL5QHiDSuAgm
w__83USCLpbx_e-cISa7hmnNlFhWLex10TS0Lw5wuLxcNTXmNt3yiHVkAJbXApeIxiNWWblpvqk8-9talYAjEBqi4nwJr59LqzWI4-4MiMtL53w6MPyLNxN6
bdu6vrPxp-RMijYozagn-zQJ5tMmhILY49mOFHTSD013u2p-tQaa6hLLAm5kk3S4tXRnwJ0u05y0zxuKlk0Blk0Blk0BvgHV09FsIvopuI2viGTXegCmfuuU
XADPEGHlY_WeJ9FPCRWluiDmAjRRu6Wf4u0-6mmWBSl27yFJVwRlZi7L3SuRBAeQ0B28X5lDCRWlwIzOnpsPpUgNRDMm68yFHVZtu_63BwHUUFnm4sSzOu3j
YuOKPuo6gGfsOwFXCCGOEuanniDWsnieh_8rZmPc-jg78Vy
}

