sprite $smart_proxy [128x127/16z] {
xTjNqgmW50JW9YC2P_-xlJyNHrudTzLuljS9AdH9nkjYZY2I0JHDXeedPQ7AU9LCOAaoL6x-TX05YQ0ISEdrkVJw77fzlRvUtnWn1YJy_a-HeO35o-11qqMa
WoUlRZI55H4BeYeDJ97T_ssWiW5KDkB2bBbm_fJcpqHSbjBygMlNlqbWKfg_ArEQFoOLmPN0epH_6LUcqk_dpzVUB6WiUP6joz3n0Q7ysPUwj9DCktj__cmO
_E8MUoDJxCLIyXTbI40QTq0GpaNEt3S30eE3oJqRC9cjP-xxpvQUkEslBJs2okqzWChL5a3bQ_NSzZUqwZAOGjiTg5Qpm9BuTq1g5l2bPY5kyQvcONtxhMGm
Tzn1kdsx4Wuv7Cr2l_VRWmrJND8f7sIwhrbeCkKfdM9SmcGHoc5RyfB-ambtSJ8TJx1iIpa4t6MNeU6HRrUyKNce-_-1mO9F0VSBoUDrIYcbb746H9jqAQ39
CcpuCBFOa_iZquSURUbBEzLQPG9B8r_Vo611OqhRBNxGFm
}

