sprite $splitter [99x66/16z] {
xTY50GGX34JHu4xwh_RSNSZf_0BshICqE3vkE467lOS00G84210WZgFV3Sc_0NpB0NdmTt4deTahOI8mS_LAal2yg7fXOb5nGeJZdOgJ9XQA7a6u46DAEPTI
Q-jya1r1-1Y2zyvPQupUluhc16wKuMrP4qaItSjztOkA8P8aUX3zkech5Vv7aHhmfvNucH_t6KCSGjWi0W4210WGsCcP0W
}

