sprite $transactional_consumer [130x55/16z] {
xPa5qYmX30QH29AG-v_sTraTgLtWoNm7w6fSukR77ipZ1WyYkXaS1eU1frH4DyPqLwGayYi6LAqmGjWO2xi2oCKgBHY0Lkm-2bWLxY1yLHWo3q2hluK8ZOVD
H6xX6X4R3LmBrFmbmXiCNOrauG9XD7W_83r7b3nyHyhb544oOKyKEa4eJ300_KMWJ3aN17yG2bCCGByHKIUTZHg_4Boq43pqCyZyXH1O6Yop0fqCGBuGYvnY
xycnXu6pJqJGDOClYUSRQFX0G5qSA_j9o_791XK-45ZSGfATfgNuJ8E27mXEbzFVXn0Z028HLxl8CmqItpQmrbH4QYqv9x6pLEXWi3mAV3O6thaEex0y4yc-
8-XSdvaOT8j13gxRQbpceBr5qVNSaLo5POCIU-tATSl9v730oHIcdSxX6o4unG3b1m4wnK3X5o4umG3b104wmK3X597hS8EQpn72WmrIktgvfi4lrok4RppG
W3LS8xncFyZ09_Kt4RdH40Dg-HuYYh3lRE1P92mW8BUQ6IDiYy6UHEHSMuQrHW2b8XjZiYib4Hp_obCC3eC_lzBr2W
}

