sprite $transactional_producer [131x55/16z] {
xPXLqWGn28I721A1-v_srtMtiDhlNVDL1fzUGdQbRe7WOlT7-210J6VAqacAS0f2e6xQwfcoUfAQMgTm625tbJZqHqJHdlVRG-tH8HPYhs6F7PMSmf4KTzgv
Wrj6GESTTcdWc9HWicL7TQuBdJRiqS0P0JIksK6JUtLC2gjsuJiKQ9OLEnYu8wn-rPQFu8kmV0PRulWYBBzhKwvtQjOrp-s2Gn48zpqoojokOIY2chNT545d
zj2dmGY_QhkUkeT_UsnZ4RhDrBO6XHR_xRaw8CnKywvuD9In2CtCzb3C4i6ORuwGKiw8HCmYHVVlJioZNY7KMee8Cn5YRhQglXgMWZwnK6of4dV6GcnE24gm
bH4-TK5cOPZsr0M7wiY_00o7gkCaD1G1hULzFSAhKuRzdV81veK7c9hkFJigFC04_LXxn1JLVPkok66dxeoWj6KNSzsicppQVM4cL7H2GCM7kpNvNzmUw-xe
VtrzZpFu1-63SAM-0G
}

