sprite $unwrapper [72x66/16z] {
xPI5ZiGm44F33F__jtSZBVh0QRRYMhJuwd76KLHQdI5JIpW14uVNhTbFpRGgK_cHFnekZFj8UVXjYgxDgBjiapSxyYE2kRHZfdJpuwFXZcBShm-tlHuRhdJx
rnh48sRoF-7trU4one1FALfnsKv_bWPlIbfPECEQOdfTy4oR4k-6kVHRKz3jWXdQbB1k1fk2fQGYJS5Ihikz7Oo67X1XKw2KcpBrPY8pCtoPf08rgu-LfbBp
7AcPs5dnFShwcoDhuFSfhilc2KSkYxQPjRbv4CxTsmRcdebmuAEZ1uuSPU3gvOMNC81pRyjgMTyE1pX7OehI9U30FHUMWW7Zm5cAoJJu1N18JEWOENnwaY1o
U4nW5JXqEtXqmY7R2YMW71OJ1iCvkBGuvZe7OxhpzZaoJuaI3ESm9GY6ShWk3jV5kJWNv-AS8tMIlW
}

