sprite $wire_tap [100x34/16z] {
xT67OG0n3090lhWNzjysRxH0cb9z2qW0VfumoHkkRYu1dYWJRvGfKuPqqwHAaKoJ7j44kUMIqnm2oLWEESqbjmI99j7aHv4gJRePCeNBZJS9N2xtqUS5RuIp
VKDatzWtzerz8vJ2KW8yJGey9Iu9dWuk1rmraXs-0ia0PoJXhR30syaJVhON
}

