sprite $wrapper [72x42/16z] {
xPGtWiCm30HNMSp__-sTunRh04CgEJs7o6ZdW5ON76Ilwxzdodd20POQ1_nxWBM60KxkKVnxRf5jy324kWBqO4p5KQQjxW0zL-QIHbZX2_7yMgR_36P0FSpM
NXZno2VlqD3fqQJjXL6FDa7Hrgh7LYQEcdgKCPVPL1ZrwDACxvR0vdbVfY7M1R1xz1d5Te-cmUlWzF3rV-7_ZIuFsyn1y7XOfip2E3na7k7mkEWUqZtTqptT
Smv_
}

